language: r
cache: packages
sudo: false

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

r:
- release
- oldrel
- devel


addons:
  apt:
    packages:
    - libicu-dev
